### ISSUE TITLE
mathjax-full removed the package **3.2.2** and led to a error

### ISSUE THREAD

**Issue by hubenchang0515** [remarkjs/remark-math#116]
### Initial checklist

- [x] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [x] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [x] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [x] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=issues) and [discussions](https://github.com/orgs/remarkjs/discussions) and couldn’t find anything (or linked relevant results below)

### Affected package

mathjax-full@3.2.1

### Steps to reproduce

https://www.npmjs.com/package/mathjax-full?activeTab=versions
mathjax-full removed the package **3.2.2**
When install rehype-mathjax, mathjax-full@**3.2.1** was installed automatically.
Then an error occorred under nextjs, (I'm not sure if other frameworks have this problem).
Install mathjax-full@**3.2.2** manually can avoid this problem: `npm i mathjax-full@3.2.2`

### Actual behavior

Error: Cannot find module '[project]/node_modules/mathjax-full/js/package.json'

### Expected behavior

work well in mathjax-full@**3.2.1** or depend on a correct version such as **3.2.2** or **4.x**

### Runtime

node@v22.20.0, next@16.0.1, react-markdown@10.1.0, remark-math@6.0.0, rehype-mathjax@7.1.0, mathjax-full@3.2.1

### Package manager

npm@10.9.3

### Operating system

Ubuntu 24.04.1 LTS

### Build and bundle tools

Next.js

**Comment by ChristianMurphy** [comment]
Welcome @hubenchang0515 👋 
This project allows any version of mathjax greater than or equal to 3.0.0 and less than 4.0.0
By default `npm` will choose the highest/latest version within that range.
https://github.com/remarkjs/remark-math/blob/76c14978ff6805011b8c56727c54104a511b9055/packages/rehype-mathjax/package.json#L13
The version conflicts you are seeing are not coming from this package.

Try running `npm update mathjax-full` to update your lock file, or deleting and re-creating your lock file.
